--- 

- name: "Template hosts file"
  template:
    src: hosts.j2
    dest: /etc/hosts 

- name: "Ensure firewalld is running"
  service:
    name: firewalld 
    state: started

- name: "Open etcd firewall ports"
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: yes
  loop: "{{ etcd_ports }}"

- name: "Set selinux boolean"
  seboolean:
    name: haproxy_connect_any
    persistent: yes 
    state: yes

- name: "Template etcd configuration"
  template:
    src: etcd.conf.j2
    dest: /etc/etcd/etcd.conf
  register: etcd_conf

- name: "Create etcd SSL directory"
  file:
    path: /etc/etcd/ssl
    state: directory

- name: "Copy client2server SSL certificates"
  copy:
    path: /etc/etcd/ssl
    src: "{{ item.file }}"
    mode: "{{ item.mode }}"
  when: etcd_ssl.enable_client2server_ssl.enable
  loop:
    - { file: "{{ etcd_ssl.enable_client2server_ssl.trusted_ca_file }}", mode: '0644' }
    - { file: "{{ etcd_ssl.enable_client2server_ssl.cert_file }}", mode: '0644' }
    - { file: "{{ etcd_ssl.enable_client2server_ssl.key_file }}", mode: '0600' }

- name: "Copy peer2peer SSL certificates"
  copy:
    path: /etc/etcd/ssl
    src: "{{ item.file }}"
    mode: "{{ item.mode }}"
  when: etcd_ssl.enable_peer2peer_ssl.enable
  loop:
    - { file: "{{ etcd_ssl.enable_peer2peer_ssl.peer_trusted_ca_file }}", mode: '0644' }
    - { file: "{{ etcd_ssl.enable_peer2peer_ssl.peer_cert_file }}", mode: '0644' }
    - { file: "{{ etcd_ssl.enable_peer2peer_ssl.peer_key_file }}", mode: '0600' }

- name: "Restart etcd service on configuration change"
  service:
    name: etcd
    state: restarted
    enabled: yes
  when: etcd_conf.changed

- name: "Start and enable etcd service"
  service:
    name: etcd
    state: started
    enabled: yes
