--- 

- name: "Template hosts file"
  template:
    src: hosts.j2
    dest: /etc/hosts 

- name: "Ensure firewalld is running"
  service:
    name: firewalld 
    state: started

- name: "Open etcd firewall ports"
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: yes
  loop: "{{ etcd_ports }}"

- name: "Set selinux boolean"
  seboolean:
    name: haproxy_connect_any
    persistent: yes 
    state: yes

- name: "Template etcd configuration"
  template:
    src: etcd.conf.j2
    dest: /etc/etcd/etcd.conf
  register: etcd_conf

- name: "Restart etcd service on configuration change"
  service:
    name: etcd
    state: restarted
    enabled: yes
  when: etcd_conf.changed

- name: "Start and enable etcd service"
  service:
    name: etcd
    state: started
    enabled: yes
