--- 

- name: "Template hosts file"
  template:
    src: hosts.j2
    dest: /etc/hosts 

- name: "Ensure firewalld is running"
  service:
    name: firewalld 
    state: started

- name: "Open firewall ports"
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: yes
  loop: "{{ firewall_ports }}"

- name: "Set selinux boolean"
  seboolean:
    name: haproxy_connect_any
    persistent: yes 
    state: yes

- name: "Template etcd configuration"
  template:
    src: etcd.conf.j2
    dest: /etc/etcd/etcd.conf
  register: etcd_conf

- name: "Restart etcd service on configuration change"
  service:
    name: etcd
    state: restarted
    enabled: yes
  when: etcd_conf.changed

- name: "Start and enable etcd service"
  service:
    name: etcd
    state: started
    enabled: yes

- name: "Create patroni configuration directory"
  file:
    path: /etc/patroni
    state: directory 

- file:
    path: /etc/patroni/etcd.conf
    state: absent

- name: "Template patroni configuration"
  template:
    src: patroni.conf.j2
    dest: /etc/patroni/patroni.conf
  register: patroni_conf

- name: "Create patroni service file"
  copy:
    src: patroni.service
    dest: /usr/lib/systemd/system/patroni.service
  register: daemon_reload

- name: "Systemd daemon-reload"
  systemd:
    daemon_reload: yes

- name: "Start and enable patroni"
  service:
    name: patroni
    state: restarted 
    enabled: yes
  when: patroni_conf.changed

- name: "Start and enable patroni"
  service:
    name: patroni
    state: started 
    enabled: yes
    