---

- name: "Install Centos7 postgres repo rpm"
  yum:
    name: "{{ centos7_pg_repo_rpm }}"
    state: present

- name: "Install epel-release repo rpm"
  yum: 
    name: epel-release 
    state: present 

- name: "Yum update"
  yum:
    name: '*'
    state: latest
  register: update

- name: "Install postgresql packages"
  yum:
    name: "{{ pg_packages }}"
    state: present 

- name: "Install patroni packages"
  yum:
    name: "{{ patroni_packages }}"
    state: present 

- name: "Install haproxy packages"
  yum:
    name: haproxy
    state: present 

- name: "Reboot"
  reboot: 
  when: update.changed
